// <auto-generated />
using Forum.WebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Forum.WebAPI.Migrations
{
    [DbContext(typeof(ForumDBContext))]
    [Migration("20211012102421_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Forum.WebAPI.Database.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            Title = "qui est esse",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            Title = "eum et est occaecati",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            Title = "nesciunt quas odio",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            Title = "magnam facilis autem",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            Title = "dolorem dolore est ipsam",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Body = "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
                            Title = "nesciunt iure omnis dolorem tempora et accusantium",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Body = "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
                            Title = "optio molestias id quia eum",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Body = "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi",
                            Title = "et ea vero quia laudantium autem",
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Body = "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio",
                            Title = "in quibusdam tempore odit est dolorem",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Body = "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam",
                            Title = "dolorum ut in voluptas mollitia et saepe quo animi",
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Body = "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum",
                            Title = "voluptatem eligendi optio",
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Body = "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae",
                            Title = "eveniet quod temporibus",
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Body = "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta",
                            Title = "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Body = "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo",
                            Title = "fugit voluptas sed molestias voluptatem provident",
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Body = "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam",
                            Title = "voluptate et itaque vero tempora molestiae",
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            Body = "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas",
                            Title = "adipisci placeat illum aut reiciendis qui",
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            Body = "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo",
                            Title = "doloribus ad provident suscipit at",
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            Body = "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt",
                            Title = "asperiores ea ipsam voluptatibus modi minima quia sint",
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            Body = "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse",
                            Title = "dolor sint quo a velit explicabo quia nam",
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            Body = "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis",
                            Title = "maxime id vitae nihil numquam",
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            Body = "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt",
                            Title = "autem hic labore sunt dolores incidunt",
                            UserId = 3
                        },
                        new
                        {
                            Id = 25,
                            Body = "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio",
                            Title = "rem alias distinctio quo quis",
                            UserId = 3
                        },
                        new
                        {
                            Id = 26,
                            Body = "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero",
                            Title = "est et quae odit qui non",
                            UserId = 3
                        },
                        new
                        {
                            Id = 27,
                            Body = "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur",
                            Title = "quasi id et eos tenetur aut quo autem",
                            UserId = 3
                        },
                        new
                        {
                            Id = 28,
                            Body = "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum",
                            Title = "delectus ullam et corporis nulla voluptas sequi",
                            UserId = 3
                        },
                        new
                        {
                            Id = 29,
                            Body = "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores",
                            Title = "iusto eius quod necessitatibus culpa ea",
                            UserId = 3
                        },
                        new
                        {
                            Id = 30,
                            Body = "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia",
                            Title = "a quo magni similique perferendis",
                            UserId = 3
                        },
                        new
                        {
                            Id = 31,
                            Body = "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae",
                            Title = "ullam ut quidem id aut vel consequuntur",
                            UserId = 4
                        },
                        new
                        {
                            Id = 32,
                            Body = "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime",
                            Title = "doloremque illum aliquid sunt",
                            UserId = 4
                        },
                        new
                        {
                            Id = 33,
                            Body = "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod",
                            Title = "qui explicabo molestiae dolorem",
                            UserId = 4
                        },
                        new
                        {
                            Id = 34,
                            Body = "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis",
                            Title = "magnam ut rerum iure",
                            UserId = 4
                        },
                        new
                        {
                            Id = 35,
                            Body = "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit",
                            Title = "id nihil consequatur molestias animi provident",
                            UserId = 4
                        },
                        new
                        {
                            Id = 36,
                            Body = "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore",
                            Title = "fuga nam accusamus voluptas reiciendis itaque",
                            UserId = 4
                        },
                        new
                        {
                            Id = 37,
                            Body = "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui",
                            Title = "provident vel ut sit ratione est",
                            UserId = 4
                        },
                        new
                        {
                            Id = 38,
                            Body = "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure",
                            Title = "explicabo et eos deleniti nostrum ab id repellendus",
                            UserId = 4
                        },
                        new
                        {
                            Id = 39,
                            Body = "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex",
                            Title = "eos dolorem iste accusantium est eaque quam",
                            UserId = 4
                        },
                        new
                        {
                            Id = 40,
                            Body = "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam",
                            Title = "enim quo cumque",
                            UserId = 4
                        },
                        new
                        {
                            Id = 41,
                            Body = "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe",
                            Title = "non est facere",
                            UserId = 5
                        },
                        new
                        {
                            Id = 42,
                            Body = "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut",
                            Title = "commodi ullam sint et excepturi error explicabo praesentium voluptas",
                            UserId = 5
                        },
                        new
                        {
                            Id = 43,
                            Body = "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis",
                            Title = "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
                            UserId = 5
                        },
                        new
                        {
                            Id = 44,
                            Body = "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae",
                            Title = "optio dolor molestias sit",
                            UserId = 5
                        },
                        new
                        {
                            Id = 45,
                            Body = "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem",
                            Title = "ut numquam possimus omnis eius suscipit laudantium iure",
                            UserId = 5
                        },
                        new
                        {
                            Id = 46,
                            Body = "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid",
                            Title = "aut quo modi neque nostrum ducimus",
                            UserId = 5
                        },
                        new
                        {
                            Id = 47,
                            Body = "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate",
                            Title = "quibusdam cumque rem aut deserunt",
                            UserId = 5
                        },
                        new
                        {
                            Id = 48,
                            Body = "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit",
                            Title = "ut voluptatem illum ea doloribus itaque eos",
                            UserId = 5
                        },
                        new
                        {
                            Id = 49,
                            Body = "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut",
                            Title = "laborum non sunt aut ut assumenda perspiciatis voluptas",
                            UserId = 5
                        },
                        new
                        {
                            Id = 50,
                            Body = "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur",
                            Title = "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
                            UserId = 5
                        },
                        new
                        {
                            Id = 51,
                            Body = "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem",
                            Title = "soluta aliquam aperiam consequatur illo quis voluptas",
                            UserId = 6
                        },
                        new
                        {
                            Id = 52,
                            Body = "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum",
                            Title = "qui enim et consequuntur quia animi quis voluptate quibusdam",
                            UserId = 6
                        },
                        new
                        {
                            Id = 53,
                            Body = "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique",
                            Title = "ut quo aut ducimus alias",
                            UserId = 6
                        },
                        new
                        {
                            Id = 54,
                            Body = "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia",
                            Title = "sit asperiores ipsam eveniet odio non quia",
                            UserId = 6
                        },
                        new
                        {
                            Id = 55,
                            Body = "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit",
                            Title = "sit vel voluptatem et non libero",
                            UserId = 6
                        },
                        new
                        {
                            Id = 56,
                            Body = "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi",
                            Title = "qui et at rerum necessitatibus",
                            UserId = 6
                        },
                        new
                        {
                            Id = 57,
                            Body = "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est",
                            Title = "sed ab est est",
                            UserId = 6
                        },
                        new
                        {
                            Id = 58,
                            Body = "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam",
                            Title = "voluptatum itaque dolores nisi et quasi",
                            UserId = 6
                        },
                        new
                        {
                            Id = 59,
                            Body = "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt",
                            Title = "qui commodi dolor at maiores et quis id accusantium",
                            UserId = 6
                        },
                        new
                        {
                            Id = 60,
                            Body = "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis",
                            Title = "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
                            UserId = 6
                        },
                        new
                        {
                            Id = 61,
                            Body = "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit",
                            Title = "voluptatem doloribus consectetur est ut ducimus",
                            UserId = 7
                        },
                        new
                        {
                            Id = 62,
                            Body = "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio",
                            Title = "beatae enim quia vel",
                            UserId = 7
                        },
                        new
                        {
                            Id = 63,
                            Body = "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta",
                            Title = "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
                            UserId = 7
                        },
                        new
                        {
                            Id = 64,
                            Body = "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui",
                            Title = "et fugit quas eum in in aperiam quod",
                            UserId = 7
                        },
                        new
                        {
                            Id = 65,
                            Body = "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur",
                            Title = "consequatur id enim sunt et et",
                            UserId = 7
                        },
                        new
                        {
                            Id = 66,
                            Body = "officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe",
                            Title = "repudiandae ea animi iusto",
                            UserId = 7
                        },
                        new
                        {
                            Id = 67,
                            Body = "reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae",
                            Title = "aliquid eos sed fuga est maxime repellendus",
                            UserId = 7
                        },
                        new
                        {
                            Id = 68,
                            Body = "magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit",
                            Title = "odio quis facere architecto reiciendis optio",
                            UserId = 7
                        },
                        new
                        {
                            Id = 69,
                            Body = "officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a",
                            Title = "fugiat quod pariatur odit minima",
                            UserId = 7
                        },
                        new
                        {
                            Id = 70,
                            Body = "sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore",
                            Title = "voluptatem laborum magni",
                            UserId = 7
                        },
                        new
                        {
                            Id = 71,
                            Body = "occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis",
                            Title = "et iusto veniam et illum aut fuga",
                            UserId = 8
                        },
                        new
                        {
                            Id = 72,
                            Body = "quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit",
                            Title = "sint hic doloribus consequatur eos non id",
                            UserId = 8
                        },
                        new
                        {
                            Id = 73,
                            Body = "voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut",
                            Title = "consequuntur deleniti eos quia temporibus ab aliquid at",
                            UserId = 8
                        },
                        new
                        {
                            Id = 74,
                            Body = "odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora",
                            Title = "enim unde ratione doloribus quas enim ut sit sapiente",
                            UserId = 8
                        },
                        new
                        {
                            Id = 75,
                            Body = "commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem",
                            Title = "dignissimos eum dolor ut enim et delectus in",
                            UserId = 8
                        },
                        new
                        {
                            Id = 76,
                            Body = "ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio",
                            Title = "doloremque officiis ad et non perferendis",
                            UserId = 8
                        },
                        new
                        {
                            Id = 77,
                            Body = "modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident",
                            Title = "necessitatibus quasi exercitationem odio",
                            UserId = 8
                        },
                        new
                        {
                            Id = 78,
                            Body = "nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus",
                            Title = "quam voluptatibus rerum veritatis",
                            UserId = 8
                        },
                        new
                        {
                            Id = 79,
                            Body = "libero accusantium et et facere incidunt sit dolorem\nnon excepturi qui quia sed laudantium\nquisquam molestiae ducimus est\nofficiis esse molestiae iste et quos",
                            Title = "pariatur consequatur quia magnam autem omnis non amet",
                            UserId = 8
                        },
                        new
                        {
                            Id = 80,
                            Body = "ex quod dolorem ea eum iure qui provident amet\nquia qui facere excepturi et repudiandae\nasperiores molestias provident\nminus incidunt vero fugit rerum sint sunt excepturi provident",
                            Title = "labore in ex et explicabo corporis aut quas",
                            UserId = 8
                        },
                        new
                        {
                            Id = 81,
                            Body = "facere qui nesciunt est voluptatum voluptatem nisi\nsequi eligendi necessitatibus ea at rerum itaque\nharum non ratione velit laboriosam quis consequuntur\nex officiis minima doloremque voluptas ut aut",
                            Title = "tempora rem veritatis voluptas quo dolores vero",
                            UserId = 9
                        },
                        new
                        {
                            Id = 82,
                            Body = "ut libero sit aut totam inventore sunt\nporro sint qui sunt molestiae\nconsequatur cupiditate qui iste ducimus adipisci\ndolor enim assumenda soluta laboriosam amet iste delectus hic",
                            Title = "laudantium voluptate suscipit sunt enim enim",
                            UserId = 9
                        },
                        new
                        {
                            Id = 83,
                            Body = "est molestiae facilis quis tempora numquam nihil qui\nvoluptate sapiente consequatur est qui\nnecessitatibus autem aut ipsa aperiam modi dolore numquam\nreprehenderit eius rem quibusdam",
                            Title = "odit et voluptates doloribus alias odio et",
                            UserId = 9
                        },
                        new
                        {
                            Id = 84,
                            Body = "sint molestiae magni a et quos\neaque et quasi\nut rerum debitis similique veniam\nrecusandae dignissimos dolor incidunt consequatur odio",
                            Title = "optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut",
                            UserId = 9
                        },
                        new
                        {
                            Id = 85,
                            Body = "similique sed nisi voluptas iusto omnis\nmollitia et quo\nassumenda suscipit officia magnam sint sed tempora\nenim provident pariatur praesentium atque animi amet ratione",
                            Title = "dolore veritatis porro provident adipisci blanditiis et sunt",
                            UserId = 9
                        },
                        new
                        {
                            Id = 86,
                            Body = "quasi excepturi consequatur iste autem temporibus sed molestiae beatae\net quaerat et esse ut\nvoluptatem occaecati et vel explicabo autem\nasperiores pariatur deserunt optio",
                            Title = "placeat quia et porro iste",
                            UserId = 9
                        },
                        new
                        {
                            Id = 87,
                            Body = "eos et molestiae\nnesciunt ut a\ndolores perspiciatis repellendus repellat aliquid\nmagnam sint rem ipsum est",
                            Title = "nostrum quis quasi placeat",
                            UserId = 9
                        },
                        new
                        {
                            Id = 88,
                            Body = "consequatur omnis est praesentium\nducimus non iste\nneque hic deserunt\nvoluptatibus veniam cum et rerum sed",
                            Title = "sapiente omnis fugit eos",
                            UserId = 9
                        },
                        new
                        {
                            Id = 89,
                            Body = "repellat aut aperiam totam temporibus autem et\narchitecto magnam ut\nconsequatur qui cupiditate rerum quia soluta dignissimos nihil iure\ntempore quas est",
                            Title = "sint soluta et vel magnam aut ut sed qui",
                            UserId = 9
                        },
                        new
                        {
                            Id = 90,
                            Body = "minus omnis soluta quia\nqui sed adipisci voluptates illum ipsam voluptatem\neligendi officia ut in\neos soluta similique molestias praesentium blanditiis",
                            Title = "ad iusto omnis odit dolor voluptatibus",
                            UserId = 9
                        },
                        new
                        {
                            Id = 91,
                            Body = "libero voluptate eveniet aperiam sed\nsunt placeat suscipit molestias\nsimilique fugit nam natus\nexpedita consequatur consequatur dolores quia eos et placeat",
                            Title = "aut amet sed",
                            UserId = 10
                        },
                        new
                        {
                            Id = 92,
                            Body = "aut et excepturi dicta laudantium sint rerum nihil\nlaudantium et at\na neque minima officia et similique libero et\ncommodi voluptate qui",
                            Title = "ratione ex tenetur perferendis",
                            UserId = 10
                        },
                        new
                        {
                            Id = 93,
                            Body = "dolorem quibusdam ducimus consequuntur dicta aut quo laboriosam\nvoluptatem quis enim recusandae ut sed sunt\nnostrum est odit totam\nsit error sed sunt eveniet provident qui nulla",
                            Title = "beatae soluta recusandae",
                            UserId = 10
                        },
                        new
                        {
                            Id = 94,
                            Body = "aspernatur expedita soluta quo ab ut similique\nexpedita dolores amet\nsed temporibus distinctio magnam saepe deleniti\nomnis facilis nam ipsum natus sint similique omnis",
                            Title = "qui qui voluptates illo iste minima",
                            UserId = 10
                        },
                        new
                        {
                            Id = 95,
                            Body = "earum voluptatem facere provident blanditiis velit laboriosam\npariatur accusamus odio saepe\ncumque dolor qui a dicta ab doloribus consequatur omnis\ncorporis cupiditate eaque assumenda ad nesciunt",
                            Title = "id minus libero illum nam ad officiis",
                            UserId = 10
                        },
                        new
                        {
                            Id = 96,
                            Body = "in non odio excepturi sint eum\nlabore voluptates vitae quia qui et\ninventore itaque rerum\nveniam non exercitationem delectus aut",
                            Title = "quaerat velit veniam amet cupiditate aut numquam ut sequi",
                            UserId = 10
                        },
                        new
                        {
                            Id = 97,
                            Body = "eum non blanditiis soluta porro quibusdam voluptas\nvel voluptatem qui placeat dolores qui velit aut\nvel inventore aut cumque culpa explicabo aliquid at\nperspiciatis est et voluptatem dignissimos dolor itaque sit nam",
                            Title = "quas fugiat ut perspiciatis vero provident",
                            UserId = 10
                        },
                        new
                        {
                            Id = 98,
                            Body = "doloremque ex facilis sit sint culpa\nsoluta assumenda eligendi non ut eius\nsequi ducimus vel quasi\nveritatis est dolores",
                            Title = "laboriosam dolor voluptates",
                            UserId = 10
                        },
                        new
                        {
                            Id = 99,
                            Body = "quo deleniti praesentium dicta non quod\naut est molestias\nmolestias et officia quis nihil\nitaque dolorem quia",
                            Title = "temporibus sit alias delectus eligendi possimus magni",
                            UserId = 10
                        },
                        new
                        {
                            Id = 100,
                            Body = "cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut",
                            Title = "at nam consequatur ea labore ea harum",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Forum.WebAPI.Database.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leanne Graham",
                            Password = "Qrqtt3vATL0m",
                            Username = "Bret",
                            Website = "hildegard.org"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ervin Howell",
                            Password = "eHCNa0kis30J",
                            Username = "Antonette",
                            Website = "anastasia.net"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clementine Bauch",
                            Password = "W0jytwzOgoM6",
                            Username = "Samantha",
                            Website = "ramiro.info"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Patricia Lebsack",
                            Password = "qpoZ6jsUaROK",
                            Username = "Karianne",
                            Website = "kale.biz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chelsey Dietrich",
                            Password = "nBxPyd64wC3H",
                            Username = "Kamren",
                            Website = "demarco.info"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mrs. Dennis Schulist",
                            Password = "ahTKyL1kBibn",
                            Username = "Leopoldo_Corkery",
                            Website = "ola.org"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kurtis Weissnat",
                            Password = "Mlr9ezVTQUKl",
                            Username = "Elwyn.Skiles",
                            Website = "elvis.io"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Nicholas Runolfsdottir V",
                            Password = "LQ8bs4y4yQDZ",
                            Username = "Maxime_Nienow",
                            Website = "jacynthe.com"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Glenna Reichert",
                            Password = "PdZJLeVPSWZm",
                            Username = "Delphine",
                            Website = "conrad.com"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Clementina DuBuque",
                            Password = "hgsQizJszlGK",
                            Username = "Moriah.Stanton",
                            Website = "ambrose.net"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Admin Admin",
                            Password = "Admin123.",
                            Username = "Admin",
                            Website = "admin.ba"
                        });
                });

            modelBuilder.Entity("Forum.WebAPI.Database.Posts", b =>
                {
                    b.HasOne("Forum.WebAPI.Database.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
